url: ""
baseurl: ""
title: "Unvergessen"
description: "Opfer rechter Gewalt in Baden-Württemberg"
collections:
  murders:
    output: true
exclude: [backup, assets]
theme: null
keep_files: [assets] # The paths are relative to the destination.  
